config/routes.rb
#
# Some of these are not used for routes right now. But we still reserve
# them for later use.
# posts is currently used in routes from the moderation mod.
#
unless defined?(FORBIDDEN_NAMES)
  FORBIDDEN_NAMES = %w[
    account admin none assets avatars chat code debug do groups
    javascripts me networks page pages people pictures places posts
    issues session static stats stylesheets theme wikis
  ].freeze
end

#  See http://guides.rubyonrails.org/v3.1.0/routing.html

Crabgrass::Application.routes.draw do
  ##
  ## CRON JOBS
  ##

  post '/do/cron/run(/:id)', to: 'cron#run', format: false,
                             constraints: { ip: /127.0.0.1/ }

  ##
  ## CSP Reports
  ##

  resource :csp_report, only: [:create]

  ##
  ## STATIC FILES AND ASSETS
  ##

  # same as the asset_path without
  resources :assets, only: [:destroy], as: 'destroy_asset'
  get '/assets/:id/versions/:version/*path',
      to: 'assets#show',
      as: 'asset_version'
  get '/assets/:id(/*path)', to: 'assets#show', as: 'asset'

  scope format: false do
    get 'avatars/:id/:size.jpg',
      to: 'avatars#show',
      as: 'avatar',
      constraints: { size: /#{Avatar::SIZES.keys.join('|')}/ }
    get 'theme/:name/*file.css', to: 'theme#show'
  end

  get 'pictures/:id1/:id2(/:geometry)',
      to: 'pictures#show',
      as: 'pictures'

  ##
  ## ME
  ##

  namespace 'me' do
    delete 'notices/destroy_all',
      to: 'notices#destroy_all',
      as: 'notices_destroy_all'
    resources :notices, only: %i[index destroy]
    get '', to: 'home#index', as: 'home'
    # resource  :page, only: [:new, :create]
    resources :recent_pages, only: [:index]
    match 'pages(/*path)', to: 'pages#index', as: 'pages', via: %i[get post]
    resources :discussions, path: 'messages', only: :index do
      resources :posts, except: [:new]
    end
    resource  :settings, only: %i[show update]
    resource  :destroy, only: %i[show update]
    resource  :password, only: %i[edit update]
    resources :permissions, only: %i[index update]
    resource  :profile, controller: 'profile', only: %i[edit update]
    resources :requests, only: %i[index update destroy show]
    resource :avatar, only: %i[create edit update destroy]
    resources :tasks, only: [:index]
  end

  ##
  ## EMAIL
  ##

  # UPGRADE: this is pre rails 3 syntax. If you want to bring these
  # routes back please upgrade them
  #  match '/invites/:action/*path', controller: 'requests', action: /accept/
  get '/code/:id', to: 'codes#jump'

  ##
  ## ACCOUNT
  ##

  resource :account, only: %i[new create]
  match 'account/reset_password(/:token)',
        as: 'reset_password',
        to: 'accounts#reset_password',
        via: %i[get post]

  post 'session/language', as: 'language', to: 'session#language'
  post 'session/login', as: 'login', to: 'session#login'
  post 'session/logout', as: 'logout', to: 'session#logout'
  # ajax login form
  get 'session/login_form', as: 'login_form', to: 'session#login_form',
                            constraints: ->(request) { request.xhr? }

  ##
  ## ENTITIES
  ##

  # autocomplete queries, restricted to ajax
  resources :entities, only: [:index],
                       constraints: ->(request) { request.xhr? }

  ##
  ## PEOPLE
  ##

  match 'people/directory(/*path)',
        as: 'people_directory',
        to: 'person/directory#index',
        via: %i[get post]

  resources :people, module: 'person', controller: 'home', only: :show do
    resource :home, only: :show, controller: 'home'
    match 'pages(/*path)', as: 'pages', to: 'pages#index', via: %i[get post]
    # resources :messages
    resource :friend_request, only: %i[new create destroy]
  end

  ##
  ## GROUP
  ##

  get 'networks/directory(/*path)',
    as: 'networks_directory',
    to: 'group/directory#index'
  get 'groups/directory(/*path)',
    as: 'groups_directory',
    to: 'group/directory#index'

  resources :groups, module: 'group', only: %i[new create destroy] do
    # content related
    resource :home, only: [:show], controller: 'home'
    match 'pages(/*path)', as: 'pages', to: 'pages#index', via: %i[get post]
    resource  :avatar, only: %i[create edit update]
    resources :wikis, only: %i[create index]

    # membership related
    resources :memberships, only: %i[index create destroy]
    resources :my_memberships, only: %i[create destroy]
    resources :membership_requests, except: %i[new edit]
    resource  :invite, only: %i[new create]

    # settings related
    resource  :settings, only: %i[show update]
    resources :requests, except: %i[new edit]
    resources :permissions, only: %i[index update]
    resource  :profile, only: %i[edit update]
    resource  :structure, only: %i[show new create update]
  end

  ##
  ## DEBUGGING
  ##

  if Rails.env.development?
    post 'debug/become', as: 'debug_become', to: 'debug#become'
    get 'debug/break', as: 'debug_break', to: 'debug#break'
  end
  # There's no bugreport controller right now it seems
  # match 'debug/report/submit', as: 'debug_report', to: 'bugreport#submit'

  ##
  ## NORMAL PAGE ROUTES
  ##

  # default page creator
  get '/pages/create(/:owner(/:type))',
      as: 'page_creation',
      to: 'page/create#new'
  post '/pages/create(/:owner(/:type))',
       to: 'page/create#create'

  # base page
  resources :pages, module: 'page', controller: 'base', only: [] do |_pages|
    resources :participations, only: %i[index update create]
    # resources :changes
    resources :assets, only: %i[index update create]
    resources :tags, only: %i[index create destroy show], :constraints => { :id => /.*/ }
    resources :posts, except: [:new]

    # page sidebar/popup controllers:
    resource :sidebar,    only: [:show]
    resource :share,      only: %i[show update],
                          constraints: ->(request) { request.xhr? }
    resource :details,    only: [:show]
    resource :history,    only: [:show], controller: 'history'
    resource :attributes, only: [:update]
    resource :title,      only: %i[edit update], controller: 'title'
    resource :trash,      only: %i[edit update destroy], controller: 'trash'
  end

  resources :posts, only: [] do |_posts|
    resource :star, only: %i[create destroy]
  end

  ##
  ## WIKI
  ##

  resources :wikis, module: 'wiki', only: %i[show edit update] do
    member do
      get 'print'
    end
    resource :lock, only: %i[destroy update]
    resources :assets, only: %i[new create]
    resources :versions, only: %i[index show] do
      member do
        post 'revert'
      end
    end
  end

  ##
  ## OTHER ROUTES
  ##

  root to: 'root#index'
  get '/do/static/greencloth', to: 'static#greencloth'

  ##
  ## SPECIAL PATH ROUTES for PAGES and ENTITIES
  ##

  resources :contexts, path: '', only: :show, constraints: { format: :html } do
    resources :pages, path: '',
                      controller: :context_pages,
                      only: %i[show edit] do
      member do
        get 'print'
      end
    end
  end

  #
  # I'm not sure we will ever want this...
  # deeply nested routes are considered a bad practice and even though
  # the url does not grow as much this basically boils down to using
  # a deeply nested approach.
  #
  # Instead we probably want
  # /pages/:page_id/...
  #
  # scope path: ':context_id/:page_id/:controller' do
  #  resources :context_page_items, path: '' do
  #    collection do
  #      post :sort
  #    end
  #  end
  # end
end

app/models/group/cache.rb
module Group::Cache
  extend ActiveSupport::Concern

  # For groups and users have two cache keys:
  # * the version based for relationships of the group.
  # * the normal one based on updated_at for the group itself
  #
  # So for example a groups network list is cached based on
  # the version cache_key so it refreshes when one of the
  # networks changes.
  #
  # The display of a network inside that list is based on that
  # networks normal cache key. It changes when the network
  # itself changes.
  def version_cache_key
    if new_record?
      cache_key
    else
      "#{self.class.model_name.cache_key}/#{id}-#{version}"
    end
  end

  module ClassMethods
    # Takes an array of group ids and increments the version of all these
    # groups. This should be called when something has changed for these groups
    # that might invalidate something they have cached on their landing page.
    # For example, when the name of a member has changed.
    # This method does not need to be called when membership is changed, the
    # version increment for that is already handled elsewhere.
    def increment_version(ids)
      return unless ids.any?
      where(id: ids).update_all('version = version+1')
    end
  end
end

app/models/group/committee.rb
class Group::Committee < Group
  ##
  ## NAMING
  ##

  # the name of a committee includes the name of the parent,
  # so the committee names are unique. however, for display purposes
  # we want to just display the committee name without the parent name.

  # committee name without parent
  def short_name
    (read_attribute(:name) || '').sub(/^.*\+/, '')
  end

  # what we show to the user
  def display_name
    read_attribute(:full_name).presence || short_name
  end

  # called when the parent's name has change
  def parent_name_changed
    self.name = short_name
  end

  # committees clean up their names a little different to make sure the group's
  # name is part of the committee's name.
  def clean_names
    super
    t_name = read_attribute(:name)
    return unless t_name
    if parent
      name_without_parent = t_name.sub(/^#{parent.name}\+/, '').tr('+', '-')
      write_attribute(:name, parent.name + '+' + name_without_parent)
    else
      write_attribute(:name, t_name.tr('+', '-'))
    end
  end

  # committees do not have committees themselves.
  def self.can_have_committees?
    false
  end

  ##
  ## PERMISSIONS
  ##

  # admin rights are restricted to members of the parents council if it exists
  # everything else can be accessed by members of the committee itself or its
  # parent group.
  # This saves us a lot of syncing of committee permissions when a groups
  # council changes.

  def has_access?(access, user)
    if access == :admin and parent.has_a_council?
      parent.has_access?(:admin, user)
    else
      super
    end
  end

  protected

  #
  # Override the way create_permissions is called in Groups.
  # For committees and councils, we call create_permissions
  # and destroy_permissions explicitly once it is added to a
  # parent group.
  #
  def call_create_permissions; end

  def call_destroy_permissions; end

  ##
  ## ORGANIZATIONAL
  ##

  private

  before_destroy :remove_from_parent
  def remove_from_parent
    parent.remove_committee!(self)
    true
  end
end

app/models/group/council.rb
class Group::Council < Group::Committee
  def add_user!(user)
    parent.clear_key_cache if parent
    super(user)
  end

  def remove_user!(user)
    parent.clear_key_cache if parent
    super(user)
  end
end

app/controllers/group/avatars_controller.rb
class Group::AvatarsController < Group::BaseController
  include_controllers 'common/avatars'
  include_controllers 'common/always_perform_caching'
  before_filter :setup

  protected

  def setup
    @entity = @group
    authorize @group, :edit?
    @success_url = group_settings_path(@group)
  end
end

app/controllers/group/base_controller.rb
class Group::BaseController < ApplicationController
  before_filter :fetch_group

  # default permission for all group controllers
  before_filter :login_required
  after_action :verify_authorized

  helper 'group/links'

  protected

  def fetch_group
    # group might be preloaded by DispatchController
    @group ||= Group.find_by_name(params[:group_id] || params[:id])
    raise_not_found if @group.nil? || !policy(@group).show?
    @membership = Group::Membership.where(group: @group, user: current_user).
      first_or_initialize
  end

  def setup_context
    @context = Context.find(@group) if @group and !@group.new_record?
    super
  end

  def new_group_committee_path(group)
    new_group_structure_path(group, type: 'committee')
  end
  helper_method :new_group_committee_path

  def new_group_council_path(group)
    new_group_structure_path(group, type: 'council')
  end
  helper_method :new_group_council_path
end

app/controllers/group/directory_controller.rb
class Group::DirectoryController < ApplicationController
  before_filter :login_required
  # skip_before_filter :login_required
  # ^^ for now, disable public directories. The old behavior was to require
  #    authentication to browse the directory, so we don't want to change this
  #    unexpectedly without either giving groups some warning or adding an
  #    additional level to the permissions.

  before_filter :set_default_path

  helper 'group/directory'

  def index
    @groups = groups_to_display.order(:name).paginate(pagination_params)
  end

  protected

  def set_default_path
    params[:path] = default_path if params[:path].empty?
  end

  def default_path
    if logged_in? && current_user.groups.any?
      'my'
    else
      'all'
    end
  end

  helper_method :my_groups?

  def my_groups?
    logged_in? && params[:path].start_with?('my')
  end

  def groups_to_display
    if search_filter
      groups_in_view.named_like("#{search_filter}%")
    else
      if my_groups?
        groups_in_view
      else
        Group.none # we might want to display promoted groups here at some point
      end
    end
  end

  def groups_in_view
    if my_groups?
      current_user.primary_groups_and_networks
    else
      Group.with_access(current_user => :view)
    end
  end

  def search_filter
    return @filter if defined?(@filter)
    @filter = get_filter_from_params
  end

  def get_filter_from_params
    if params[:q].present?
      params[:q]
    elsif params[:path].include? 'search/'
      params[:path].sub(/.*search\//, '')
    end
  end
end

app/controllers/group/groups_controller.rb
class Group::GroupsController < Group::BaseController
  include Common::Tracking::Action

  before_filter :initialize_group, only: %w[new create]
  before_filter :fetch_group, only: :destroy
  before_filter :fetch_associations, only: :destroy

  after_filter :notify_former_users, only: :destroy


  def new
    authorize @group
  end

  #
  # responsible for creating groups and networks.
  # councils and committees are created by groups/structures
  #
  def create
    authorize @group
    @group.save!
    current_user.reload # may have gained access to new group
    @group.add_user!(current_user) unless @group.network? && policy(@group).admin?
    success :group_successfully_created.t
    redirect_to group_url(@group)
  end

  #
  # immediately destroy a group.
  # for destruction that requires approval, see RequestToDestroyOurGroup.
  # unlike creation, all destruction of all group types is handled here.
  #
  def destroy
    authorize @group
    @group.destroy
    success :thing_destroyed.t(thing: @group.name)
    redirect_to group_destroyed_redirect
  end

  protected

  # load all associations we need after the group was destroyed
  def fetch_associations
    @group = Group.where(id: @group.id).includes(:users, :parent).first
  end

  def notify_former_users
    notification = Notification.new(:group_destroyed, group: @group, user: current_user)
    notification.deliver_mails_to(@group.users, mailer_options)
    notification.create_notices_for(@group.users, group: @group)
  end

  def group_destroyed_redirect
    if @group.parent
      group_url(@group.parent)
    else
      me_url
    end
  end

  def group_type
    if Conf.networks && params[:type].to_s == 'network'
      :network
    elsif %w/council committee/.include? params[:type].to_s
      params[:type].to_sym
    else
      :group
    end
  end
  helper_method :group_type

  def group_class
    group_type == :network ? Group::Network : Group
  end

  def initialize_group
    @group = group_class.new group_params
    @group.created_by = current_user
    @group.initial_member_group = member_group if group_type == :network
  end

  def group_params
    params.fetch(:group, {}).permit :name, :full_name, :language
  end

  def member_group
    name = params.fetch(:group, {})[:initial_member_group]
    Group.where(name: name).first.tap do |group|
      current_user.may!(:admin, group)
    end
  end
end

app/controllers/group/home_controller.rb
class Group::HomeController < Group::BaseController
  skip_before_filter :login_required

  before_filter :fetch_wikis
  after_filter :track_visit, if: :logged_in?

  layout 'sidecolumn'
  helper 'wikis/base', 'wikis/sections'

  def initialize(options = {})
    super()
    @group = options[:group]
  end

  def show
    authorize @group
    @pages = Page.paginate_by_path '/descending/updated_at/limit/30/',
                                   options_for_group(@group), pagination_params
  end

  protected

  def fetch_wikis
    @private_wiki = fetch_wiki(:private) if policy(@group).edit?
    @public_wiki = fetch_wiki(:public)
  end

  def fetch_wiki(type)
    @group.profiles.send(type).try.wiki.tap do |wiki|
      return nil if wiki.blank? || wiki.body.blank?
      wiki.last_seen_at = last_visit
    end
  end

  def last_visit
    memberships.pluck(:visited_at).first if logged_in?
  end

  def track_visit
    memberships.update_all(visited_at: Time.now)
  end

  def memberships
    @group.memberships.where(user_id: current_user)
  end

end

app/views/group/structures/_new_form.html.haml
-#
-# All groups of all types are created via this partial.
-#
-# This is used by the creation code in both groups/group_controller
-# and groups/structures_controller.
-#
-# requires:
-#
-#   group_type -- symbol of :group, :network, :committee, :council
-#

- if group_type == :committee || group_type == :council
  - url = group_structure_path(@group)
- else
  - url = groups_path

- if group_type == :group
  - thing = :organization
- else
  - thing = group_type

- content_for :title do
  %h1= :create_a_new_thing.t(thing: thing.t)

= form_for(@committee || @group, url: url) do |form|

  = hidden_field_tag 'type', params[:type]

  = formy(:horizontal_form) do |f|

    - f.label content_tag(:p, "#{group_type}_description".to_sym.t, class: "p icon medium #{group_type}_48")

    - f.row do |r|
      - r.label :name.t
      - r.label_for :group_name
      - r.input form.text_field('name', class: 'form-control')
      - r.info "(#{:required.t}) "
      - r.info :link_name_description.t

    - f.row do |r|
      - r.label :display_name.t
      - r.label_for 'group_full_name'
      - r.input form.text_field('full_name', class: 'form-control')
      - r.info "(#{:optional.t}) "
      - r.info I18n.t(:descriptive_name_for_display)

    - if group_type == :network
      - f.row do |r|
        - r.label :group.t
        - r.label_for :group_initial_member_group
        - r.input form.select('initial_member_group', options_for_select_group(as_admin: true, without_networks: true, selected: @group.initial_member_group), {}, class: 'form-control')
        - r.info "(#{:required.t}) "
        - r.info :network_initial_member.t

    - f.row do |r|
      - r.label I18n.t(:language)
      - r.label_for 'group_language'
      - r.input form.select('language', all_languages_for_select, {include_blank: true}, {class: 'form-control'})
      - r.info "(#{:optional.t}) "
      - r.info :group_language.t(group: t(group_type.downcase))

      -# adding avatar wasn't working, and seems okay for now to have it added under settings

    - f.button submit_tag(:create_button.t, class: 'btn btn-primary')

app/views/group/structures/_show_in_sidebar.html.haml
-#
-# note: the cache needs to go within the permission check
-# otherwise we are caching stuff for people who shouldn't see it.
-#
- if policy(@group).may_list_group_committees?
  - if @group.real_committees.size > 0
    = entity_list @group.real_committees.order(:name),
      header: :committees.t
    -# , after: link_line(create_committee_link))
  - if @group.has_a_council?
    = entity_list([@group.council], header: :council.t)
- if @group.network? and policy(@group).may_list_memberships?
  = entity_list @group.groups.order(:name),
    header: :member_groups_of_network.t
  -#after: link_line(:bullet, list_memberships_link, invite_link, requests_link))
- if policy(@group).may_list_group_networks?
  = entity_list @group.networks.order(:name),
    header: :networks.t

app/views/group/structures/new.html.haml
= render "new_form"

app/views/group/structures/show.html.haml
= formy(:horizontal_form) do |f|
  - if policy(@group).may_list_group_committees?
    - f.row do |r|
      - r.label :council.t
      - if @group.has_a_council?
        - r.input link_to_group(@group.council, avatar: :small)
      - else
        - r.input link_line(:bullet, :none.t, create_council_link)
      - r.info :council_description.t
      - if !@group.has_a_council?
        - r.info content_tag(:div, :council_description_details.t(group: @group.group_type), class: 'p')
    - f.row do |r|
      - r.label :committees.t
      - if @group.real_committees.any?
        - r.input entity_list(@group.real_committees, avatar: 'small', class: 'spaced', footer: link_to(:create_a_new_thing.t(thing: :committee.t), new_group_committee_path(@group)))
      - elsif policy(@group).may_create_committee?
        - r.input link_line :bullet, :none.t, link_to(:create_a_new_thing.t(thing: :committee.t), new_group_committee_path(@group))
      - r.info :committee_description.t
  - if policy(@group).may_list_group_networks?
    - f.row do |r|
      - r.label :networks.t
      - if @group.networks.any?
        - r.input entity_list(@group.networks, avatar: 'small', class: 'spaced')
      - else
        - r.input :none.t
      - r.info :network_description.t
  - if destroy_group_link.present?
    - f.row do |r|
      - r.label :structure.t
      - r.input destroy_group_link