config/routes.rb
#
# Some of these are not used for routes right now. But we still reserve
# them for later use.
# posts is currently used in routes from the moderation mod.
#
unless defined?(FORBIDDEN_NAMES)
  FORBIDDEN_NAMES = %w[
    account admin none assets avatars chat code debug do groups
    javascripts me networks page pages people pictures places posts
    issues session static stats stylesheets theme wikis
  ].freeze
end

#  See http://guides.rubyonrails.org/v3.1.0/routing.html

Crabgrass::Application.routes.draw do
  ##
  ## CRON JOBS
  ##

  post '/do/cron/run(/:id)', to: 'cron#run', format: false,
                             constraints: { ip: /127.0.0.1/ }

  ##
  ## CSP Reports
  ##

  resource :csp_report, only: [:create]

  ##
  ## STATIC FILES AND ASSETS
  ##

  # same as the asset_path without
  resources :assets, only: [:destroy], as: 'destroy_asset'
  get '/assets/:id/versions/:version/*path',
      to: 'assets#show',
      as: 'asset_version'
  get '/assets/:id(/*path)', to: 'assets#show', as: 'asset'

  scope format: false do
    get 'avatars/:id/:size.jpg',
      to: 'avatars#show',
      as: 'avatar',
      constraints: { size: /#{Avatar::SIZES.keys.join('|')}/ }
    get 'theme/:name/*file.css', to: 'theme#show'
  end

  get 'pictures/:id1/:id2(/:geometry)',
      to: 'pictures#show',
      as: 'pictures'

  ##
  ## ME
  ##

  namespace 'me' do
    delete 'notices/destroy_all',
      to: 'notices#destroy_all',
      as: 'notices_destroy_all'
    resources :notices, only: %i[index destroy]
    get '', to: 'home#index', as: 'home'
    # resource  :page, only: [:new, :create]
    resources :recent_pages, only: [:index]
    match 'pages(/*path)', to: 'pages#index', as: 'pages', via: %i[get post]
    resources :discussions, path: 'messages', only: :index do
      resources :posts, except: [:new]
    end
    resource  :settings, only: %i[show update]
    resource  :destroy, only: %i[show update]
    resource  :password, only: %i[edit update]
    resources :permissions, only: %i[index update]
    resource  :profile, controller: 'profile', only: %i[edit update]
    resources :requests, only: %i[index update destroy show]
    resource :avatar, only: %i[create edit update destroy]
    resources :tasks, only: [:index]
  end

  ##
  ## EMAIL
  ##

  # UPGRADE: this is pre rails 3 syntax. If you want to bring these
  # routes back please upgrade them
  #  match '/invites/:action/*path', controller: 'requests', action: /accept/
  get '/code/:id', to: 'codes#jump'

  ##
  ## ACCOUNT
  ##

  resource :account, only: %i[new create]
  match 'account/reset_password(/:token)',
        as: 'reset_password',
        to: 'accounts#reset_password',
        via: %i[get post]

  post 'session/language', as: 'language', to: 'session#language'
  post 'session/login', as: 'login', to: 'session#login'
  post 'session/logout', as: 'logout', to: 'session#logout'
  # ajax login form
  get 'session/login_form', as: 'login_form', to: 'session#login_form',
                            constraints: ->(request) { request.xhr? }

  ##
  ## ENTITIES
  ##

  # autocomplete queries, restricted to ajax
  resources :entities, only: [:index],
                       constraints: ->(request) { request.xhr? }

  ##
  ## PEOPLE
  ##

  match 'people/directory(/*path)',
        as: 'people_directory',
        to: 'person/directory#index',
        via: %i[get post]

  resources :people, module: 'person', controller: 'home', only: :show do
    resource :home, only: :show, controller: 'home'
    match 'pages(/*path)', as: 'pages', to: 'pages#index', via: %i[get post]
    # resources :messages
    resource :friend_request, only: %i[new create destroy]
  end

  ##
  ## GROUP
  ##

  get 'networks/directory(/*path)',
    as: 'networks_directory',
    to: 'group/directory#index'
  get 'groups/directory(/*path)',
    as: 'groups_directory',
    to: 'group/directory#index'

  resources :groups, module: 'group', only: %i[new create destroy] do
    # content related
    resource :home, only: [:show], controller: 'home'
    match 'pages(/*path)', as: 'pages', to: 'pages#index', via: %i[get post]
    resource  :avatar, only: %i[create edit update]
    resources :wikis, only: %i[create index]

    # membership related
    resources :memberships, only: %i[index create destroy]
    resources :my_memberships, only: %i[create destroy]
    resources :membership_requests, except: %i[new edit]
    resource  :invite, only: %i[new create]

    # settings related
    resource  :settings, only: %i[show update]
    resources :requests, except: %i[new edit]
    resources :permissions, only: %i[index update]
    resource  :profile, only: %i[edit update]
    resource  :structure, only: %i[show new create update]
  end

  ##
  ## DEBUGGING
  ##

  if Rails.env.development?
    post 'debug/become', as: 'debug_become', to: 'debug#become'
    get 'debug/break', as: 'debug_break', to: 'debug#break'
  end
  # There's no bugreport controller right now it seems
  # match 'debug/report/submit', as: 'debug_report', to: 'bugreport#submit'

  ##
  ## NORMAL PAGE ROUTES
  ##

  # default page creator
  get '/pages/create(/:owner(/:type))',
      as: 'page_creation',
      to: 'page/create#new'
  post '/pages/create(/:owner(/:type))',
       to: 'page/create#create'

  # base page
  resources :pages, module: 'page', controller: 'base', only: [] do |_pages|
    resources :participations, only: %i[index update create]
    # resources :changes
    resources :assets, only: %i[index update create]
    resources :tags, only: %i[index create destroy show], :constraints => { :id => /.*/ }
    resources :posts, except: [:new]

    # page sidebar/popup controllers:
    resource :sidebar,    only: [:show]
    resource :share,      only: %i[show update],
                          constraints: ->(request) { request.xhr? }
    resource :details,    only: [:show]
    resource :history,    only: [:show], controller: 'history'
    resource :attributes, only: [:update]
    resource :title,      only: %i[edit update], controller: 'title'
    resource :trash,      only: %i[edit update destroy], controller: 'trash'
  end

  resources :posts, only: [] do |_posts|
    resource :star, only: %i[create destroy]
  end

  ##
  ## WIKI
  ##

  resources :wikis, module: 'wiki', only: %i[show edit update] do
    member do
      get 'print'
    end
    resource :lock, only: %i[destroy update]
    resources :assets, only: %i[new create]
    resources :versions, only: %i[index show] do
      member do
        post 'revert'
      end
    end
  end

  ##
  ## OTHER ROUTES
  ##

  root to: 'root#index'
  get '/do/static/greencloth', to: 'static#greencloth'

  ##
  ## SPECIAL PATH ROUTES for PAGES and ENTITIES
  ##

  resources :contexts, path: '', only: :show, constraints: { format: :html } do
    resources :pages, path: '',
                      controller: :context_pages,
                      only: %i[show edit] do
      member do
        get 'print'
      end
    end
  end

  #
  # I'm not sure we will ever want this...
  # deeply nested routes are considered a bad practice and even though
  # the url does not grow as much this basically boils down to using
  # a deeply nested approach.
  #
  # Instead we probably want
  # /pages/:page_id/...
  #
  # scope path: ':context_id/:page_id/:controller' do
  #  resources :context_page_items, path: '' do
  #    collection do
  #      post :sort
  #    end
  #  end
  # end
end

app/helpers/common/page/search_helper.rb
#
#
# Here lie all the helpers for the fancy search form for pages.
#
# For many of the methods in this helper to work, 'page_search_path()' must be defined.
# Typically, this will call me_pages_path or group_pages_path.
#

require 'cgi'

module Common::Page::SearchHelper
  protected

  def search_filter_sections
    %i[my_pages access properties popular_pages advanced]
  end

  # def opened_section?(section)
  #  [:my_pages].include?(section)
  # end

  # creates a quick lookup map of filter => true for the currently active filters
  def active_filters
    @active_filters ||= @path.filters.to_h { |f| [f[0], true] }
  end

  # returns true if the filter is active in the current path
  def filter_active?(filter)
    active_filters[filter]
  end

  #
  # Returns true if the specified filter should not be shown.
  #
  # There are two reasons to hide a filter:
  #
  # (1) some filters are incompatible with other filters. The filter definition
  #     for these filters will include filter.exclude. This will be a symbol
  #     that defines a set of mutually exclusive filters (e.g. :popular_pages).
  # (2) the current controller can define 'include_filter?(filter)'. If it returns
  #     false, then the filter is excluded.
  #
  def filter_excluded?(filter)
    @excluded_filters ||= begin
      @path.filters.to_h { |f| [f[0].exclude, true] }
    end
    if !show_filter?(filter)
      true
    elsif filter.exclude
      @excluded_filters[filter.exclude]
    else
      false
    end
  end

  def possible_filters_for_section(section)
    enabled = []
    disabled = []
    SearchFilter.filters_for_section(section).each do |filter|
      if filter_active?(filter)
      # ignore?
      elsif filter_excluded?(filter)
        disabled.push(filter)
      else
        enabled.push(filter)
      end
    end
    [enabled, disabled]
  end

  def filter_all
    SearchFilter['all']
  end

  #
  # if we should show the 'all' filter, return true.
  #
  def show_all?
    @show_all ||= !(@path.filters.detect { |filter, _x| filter.has_label? })
  end

  #
  # mode: must be :add or :remove
  #
  def filter_checkbox_li_tag(mode, filter, args = nil, options = {})
    if filter.has_args?
      filter_multivalue_li_tag(mode, filter, args, options)
    else
      filter_singlevalue_li_tag(mode, filter, options)
    end
  end

  #
  # for filters with no args
  #
  def filter_singlevalue_li_tag(mode, filter, options)
    label = filter.label(nil, mode => true, :current_user => current_user)
    if options[:disabled]
      link_to_function(label, '', icon: 'check_off', class: 'disabled')
    else
      spinbox_tag(filter.path_keyword,
                  page_search_path(mode => filter.path_definition),
                  label: label,
                  with: 'FilterPath.encode()',
                  checked: (mode == :remove))
    end
  end

  #
  # for filters with one or more args
  #
  def filter_multivalue_li_tag(mode, filter, args, options)
    label = filter.label(args, mode => true, :current_user => current_user)
    if options[:disabled]
      link_to_function(label, '', icon: 'check_off', class: 'disabled')
    elsif mode == :add
      link_to_static_modal label, icon: 'check_off' do
        render 'common/pages/search/popup',
               url: page_search_path(add: filter.path_definition),
               filter: filter
      end
    elsif mode == :remove
      if label
        path = filter.path(args)
        name = filter.name(args)
        spinbox_tag(name, page_search_path(remove: path),
                    label: label,
                    with: 'FilterPath.encode()',
                    checked: true)
      end
    end
  end

  #
  # a link used in the page search popup.
  # it creates a form element to match params, then submits the form.
  # this only accepts a single param, but it is in the form {:key => value}
  #
  def link_to_page_search(label, params, _options = {})
    # we need to encode the values so you can't XSS out of the js function
    name, value = params.to_a.first.map { |i| CGI.escape(i.to_s) }
    # we need to decode the values when they are inserted into the form so
    # the form submission does not lead to duplicate encoding...
    function = format("$('page_search_form').insert(new Element('input', {name:decodeURIComponent('%s'), value:decodeURIComponent('%s'), style:'display:none'})); $('page_search_form').submit.click();", name, value)
    link_to_function(label, function)
  end
end

app/views/common/pages/search/_controls_active.html.haml
%ul#search_controls_active.page_search_controls
  .section.first= :active_filters.t
  - if show_all?
    = filter_checkbox_li_tag :remove, filter_all
  - else
    - @path.filters.each do |filter, args|
      = filter_checkbox_li_tag :remove, filter, args

app/views/common/pages/search/_controls_possible.html.haml
%ul#search_controls_possible.page_search_controls
  - unless show_all?
    = filter_checkbox_li_tag :add, filter_all
  - for section in search_filter_sections
    - enabled_filters, disabled_filters = possible_filters_for_section(section)
    - id = "#{section}_section"
    - if enabled_filters.any? || disabled_filters.any?
      %li
        .section= section.tcap
        %ul
          - for filter in enabled_filters
            = filter_checkbox_li_tag :add, filter
          - for filter in disabled_filters
            = filter_checkbox_li_tag :add, filter, nil, disabled: true

-# for expanding sections:
-#  = link_to_toggle(section.to_s, id, open: opened_section?(section))
-#  %ul{id: id, style: (opened_section?(section) ? '' : 'display:none')}
-#    - for filter in SearchFilter.filters_for_section(section)
-#      - next if filter_active?(filter)
-#      %li
-#        = filter_checkbox_li_tag :add, filter

app/views/common/pages/search/_create.html.haml
.p.first
  - if @group
    = link_to :create_page.t, new_page_path(owner: @group), icon: 'plus'
  - else
    = link_to :create_page.t, new_page_path, icon: 'plus'

app/views/common/pages/search/_popup.html.haml
-#
-# This is used to generate the content for search filter popups
-#
-# requires variables:
-# * filter
-# * url
-#
-# search filters can set these html options to control how the popup is displayed:
-#
-# :submit_button -- if true, include an extra submit button in the popup.
-#                   otherwise we still include the button, but hidden
-#                   (because of how form_tag and :with work, we use this button for all submits).
-#
-#
-# notes:
-#
-# When calculating the path, params submitted in this form are used to substitute
-# into the path. For example,
-#
-#   if params['user_id']  --> 'green', then
-#   /created-by/:user_id/ --> /created-by/green/
-#

- with = "FilterPath.encode()+'&'+Form.serialize(this.form)"
- @filter_submit_options = {url: url, with: with, loading: show_spinner('search_filter'), complete: close_modal_function}

= form_tag(url, id: 'page_search_form') do
  - if filter.description.present?
    .tip.info_16
      = filter.description.t
  = self.instance_eval(&filter.html_block)
  .buttons-right
    - if filter.options[:submit_button]
      = spinner('search_filter')
      = close_modal_button
      = button_to_function :search.t, remote_function(@filter_submit_options), class: 'btn btn-primary', name: 'submit'
    - else
      = text_spinner('loading...', 'search_filter')
      = button_to_function '', remote_function(@filter_submit_options), style: 'display:none', name: 'submit'

app/views/common/pages/search/_top_controls.html.haml
-#
-# this is a partial for the top search controls.
-# which contain a text filter field and view controls.
-#
-# REQUIREMENTS
-#
-#   page_search_path must be defined.
-#
-# NOTES
-#
-#   because we are not using form_remote_tag, we eat the return key and trigger a click
-#   to the submit link.
-#
-#   if the contents of the search text field are empty, then the params get set to :remove
-#   instead of :add. ie params[:add] -> '/text/:text/'.
-#   The :text is replaced with params[:text] by the path parser.
-#

-#
-# options for text filter form
-#
- add_or_remove = "($('search_text_field').value ? 'add' : 'remove')+'=/text/:text/'"
- with = "#{add_or_remove}+'&'+FilterPath.encode()+'&'+Form.serialize($('page_search_form'))"
- clear_filter_options = "'remove=/text/:text/'+'&'+FilterPath.encode()"
- key_pressed = "if (enterPressed(event)) {$('search_submit').click(); return false;}"

#page_search_table
  %div
    = spinner('view_toggle')
  %div.p
    = form_tag '', id: 'page_search_form', class: 'form-inline' do
      .input-group
        %span.input-group-btn
          = link_to icon_tag('tiny_clear'), page_search_path,
              remote: true,
              method: :post,
              data: { with: clear_filter_options },
              class: 'btn btn-default btn-sm'
        = text_field_tag 'text', '', size: 40, id: 'search_text_field', onkeypress: key_pressed, placeholder: :search.t, class: 'form-control input-sm'
        %span.input-group-btn
          = link_to icon_tag('magnifier'), page_search_path,
              remote: true,
              method: :post,
              data: { with: with },
              id: 'search_submit',
              class: 'btn btn-default btn-sm'
= focus_form 'page_search_form'

app/views/common/pages/search/index.html.haml
- @local_layout = 'sidebar'
- content_for :title do
  = render 'layouts/section/heading_with_info', section: :page_search, first: true
= render 'common/pages/search/top_controls'

#search_results{data: {search: 'path', href: page_search_path}}
  - if @path.present?
    = render 'common/pages/list', local_assigns
  - else
    = big_spinner